### ISSUE TITLE
砸金蛋组件功能期望优化

### ISSUE THREAD

**Issue by R-yan** [jdf2e/nutui-bingo#11]
1.砸金蛋组件期望暴露当前点击的金蛋的下标和当前金蛋的原数据对象  
2.砸金蛋组件期望能够接收【已砸金蛋数组】进行初始化组件，来满足用户刷新后砸过的金蛋能够回显的需求

感谢作者开源 🙏

**Comment by Ymm0008** [comment]
感谢反馈，正在跟进 @R-yan
