### ISSUE TITLE
在NutUI4项目中无法使用

### ISSUE THREAD

**Issue by ben5473** [jdf2e/nutui-bingo#12]
尝鲜用 taro + NutUI4 新建项目，并安装bingo，运行报错：

ERROR in ./src/pages/index/index.vue?vue&type=template&id=1badc801 (./node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-vue-components!./node_modules/babel-loader/lib/index.js??clonedRuleSet-11.use[0]!./node_modules/vue-loader/dist/templ
ateLoader.js??ruleSet[1].rules[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/index/index.vue?vue&type=template&id=1badc801) 1:112-170
Module not found: Error: Can't resolve '@nutui/nutui-taro/dist/packages/bigmarquee/style' in

在NutUI3下使用正常

**Comment by Ymm0008** [comment]
抱歉，目前bingo不支持NutUI 4.0使用，尚未兼容，后期更新会同步此内容。 @ben5473
