### ISSUE TITLE
能不能别在taro版本里面写div代码？你们是jd程序员吗

### ISSUE THREAD

**Issue by sparGuan** [jdf2e/nutui-bingo#25]
好意思么，这点基础都没有？不能在taro里面写html标签
![image](https://github.com/jdf2e/nutui-bingo/assets/28480563/fb21195a-4098-4aa2-821a-8bde111a24cf)

**Comment by eiinu** [comment]
有没有可能是你基础不行？ https://taro-docs.jd.com/docs/use-h5
