### ISSUE TITLE
刮刮卡回调事件问题

### ISSUE THREAD

**Issue by ldxm** [jdf2e/nutui-bingo#3]
src\packages\__VUE\scratchcard\index.vue ---目标路径
![image](https://user-images.githubusercontent.com/42989883/189085832-81d2cedb-26e8-45b1-8f36-981575ea256c.png)
图中方法，会改变回调事件导致，刮开后执行到该回调中。

**Comment by Ymm0008** [comment]
@ldxm  收到，正在处理中

**Comment by Ymm0008** [comment]
@ldxm  问题已处理，已发版，1.0.6-beta.1
