### ISSUE TITLE
抽奖机的 BUG，不中奖显示三个图片一样

### ISSUE THREAD

**Issue by roymax** [jdf2e/nutui-bingo#4]
当后端返回不中奖时，设置 prizeIndex = -1  ，但抽奖机还是显示三个图片一样。
在官网验证也会出现这个问题：

1. 点击不中奖按钮（双击后出现概率会很高）
2. 显示三个图片一样

以下图片都是通过双击「不中奖」按钮出现的
![288851666064054_ pic](https://user-images.githubusercontent.com/409619/196330554-8da46ed2-29d4-4826-bd1e-1fb0739d03e4.jpg)
![288861666064201_ pic](https://user-images.githubusercontent.com/409619/196330561-0ef2ef09-8d2f-4c58-94d4-74de0be7daae.jpg)
![288871666064232_ pic](https://user-images.githubusercontent.com/409619/196330564-991fab5d-b5aa-4bed-958d-cc5a1018e96e.jpg)

**Comment by Ymm0008** [comment]
@roymax  感谢反馈，正在排查。

**Comment by Ymm0008** [comment]
@roymax  您好，问题已处理，下周发布，目前已在dev分支修补

**Comment by Ymm0008** [comment]
https://www.npmjs.com/package/@nutui/nutui-bingo/v/1.0.7-beta.0
