### ISSUE TITLE
支持 taro + vue3吗？

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui-bingo#5]
进入组件，点击taro时又会跳转至首页，是不支持吗
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/43030980/198482839-baf2da36-5b1d-40f9-af5a-473219800f38.png">

**Comment by Ymm0008** [comment]
@yanbowe   您好，这个组件库就是使用的 vue3 开发，可以支持。可能官网文档有些问题，我这边看一下。

使用方式是这样的
`
// vue

import { Turntable } from '@nutui/nutui-bingo';

// taro

import { Turntable } from '@nutui/nutui-bingo-taro';
`

**Comment by yanbowe** [comment]
> @yanbowe 您好，这个组件库就是使用的 vue3 开发，可以支持。可能官网文档有些问题，我这边看一下。
> 
> 使用方式是这样的 ` // vue
> 
> import { Turntable } from '@nutui/nutui-bingo';
> 
> // taro
> 
> import { Turntable } from '@nutui/nutui-bingo-taro'; `

好的谢谢您

**Comment by txl1123** [comment]
你好，引入之后在taro-vue里依旧不显示，
<img width="375" alt="image" src="https://user-images.githubusercontent.com/9738404/198825552-d8d35ff6-dd3f-4515-a2a2-7ca16ef75108.png">
<img width="459" alt="image" src="https://user-images.githubusercontent.com/9738404/198825561-fa8c5703-fcee-4235-be41-1c0cb082f248.png">
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/9738404/198825587-8f8f9943-51ce-4ecd-b934-193cd58033d7.png">

**Comment by yanbowe** [comment]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/43030980/198913290-37ef4671-22ee-4b0b-88cf-6f41e76f639f.png">
![image](https://user-images.githubusercontent.com/43030980/198913404-afd004eb-1af4-4c40-a55e-ae93e29da001.png)

taro使用方式和vue是一样的吗，我这边运行有报错@Ymm0008

**Comment by yanbowe** [comment]
文档可否添加taro使用方式呀

**Comment by Ymm0008** [comment]
@yanbowe 使用方式是一样的，我这边本地看下，您最好提供一下复现的代码和taro的依赖版本

**Comment by Ymm0008** [comment]
![](https://img13.360buyimg.com/imagetools/s200x200_jfs/t1/187308/9/29678/349561/634fa983E93012590/a641089fdfed5911.png)  @yanbowe 可以加我咱俩方便交流

**Comment by yanbowe** [comment]
> ![](https://camo.githubusercontent.com/6699b62cef819d47c4f933594a252e8edbb7a51c0fbfe0b53a12f886aa840e9f/68747470733a2f2f696d6731332e333630627579696d672e636f6d2f696d616765746f6f6c732f73323030783230305f6a66732f74312f3138373330382f392f32393637382f3334393536312f36333466613938334539333031323539302f613634313038396664666564353931312e706e67) @yanbowe 可以加我咱俩方便交流
好的
