### ISSUE TITLE
在Taro+Vue3里无法使用，不显示内容

### ISSUE THREAD

**Issue by txl1123** [jdf2e/nutui-bingo#6]
引入之后在taro-vue项目里，编译完成不报错，但是在开发工具里查看不显示
<img width="375" alt="image" src="https://user-images.githubusercontent.com/9738404/198825552-d8d35ff6-dd3f-4515-a2a2-7ca16ef75108.png">
<img width="459" alt="image" src="https://user-images.githubusercontent.com/9738404/198825561-fa8c5703-fcee-4235-be41-1c0cb082f248.png">
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/9738404/198825587-8f8f9943-51ce-4ecd-b934-193cd58033d7.png">

**Comment by Ymm0008** [comment]
@txl1123  好的，我这边正在排查

**Comment by Ymm0008** [comment]
@txl1123  感谢反馈，问题已修复，并发布新的npm包，辛苦替换使用，有问题随时沟通。https://www.npmjs.com/package/@nutui/nutui-bingo-taro/v/1.0.7-beta.1

**Comment by Ymm0008** [comment]
![](https://img13.360buyimg.com/imagetools/s200x200_jfs/t1/187308/9/29678/349561/634fa983E93012590/a641089fdfed5911.png)  @txl1123  有问题可以加我，方便沟通
