### ISSUE TITLE
大转盘的单位不是自适应单位

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui-bingo#7]
在h5中或小程序中不会转化rpx或rem单位，是需要额外处理吗？
ps：像九宫格或跑马灯这两个组件是会转化为rpx的,不过h5中不是rem单位，还是px单位
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/43030980/199408984-a818caf9-2f7b-4a10-83a9-940001478fa8.png">

**Comment by yanbowe** [comment]
![image](https://user-images.githubusercontent.com/43030980/199422265-8a8b264d-6e78-49bf-a083-ed118e98d01f.png)
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/43030980/199422428-aef98684-e5fb-4dfb-af22-5c859f8709eb.png">

使用Taro.pxTransform(300)转化为自适应单位，无法显示背景色

**Comment by Ymm0008** [comment]
实现方案需要考虑一下，目前暂不支持转换，本需求已加入计划中。
