### ISSUE TITLE
SquareNine 九宫格组件问题

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui-bingo#8]
1. 小程序上没有中奖的图片显示有问题，没有显示对应id的奖品图片
2. 连续翻转2张牌，位置就错乱了， 官网可以复现
3. 在微信小程序中，收牌的位置没有完全隐藏在翻牌按钮下
<img width="492" alt="image" src="https://user-images.githubusercontent.com/43030980/199409263-348b270c-be23-48f1-8c37-542bee0de2e0.png">

**Comment by Ymm0008** [comment]
1
