### ISSUE TITLE
LottoRoll  摇奖机在taro中编译到h5点击抽奖报错

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui-bingo#9]
taro编译到小程序是正常的，在h5中报错
taro 3.5.7 
@nutui/nutui-bingo-taro 1.0.7-beta.1
vue 3.2.41
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/43030980/199419608-47277761-f04a-4be8-9b52-528a6c6afa41.png">

**Comment by Ymm0008** [comment]
最新版本是1.0.7-beta.2，可以重新安装使用。 @yanbowe

**Comment by yanbowe** [comment]
> 最新版本是1.0.7-beta.2，可以重新安装使用。 @yanbowe

还是一样的错误
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/43030980/200217625-46ad9aaf-a782-4656-b121-06b210dbde1c.png">

**Comment by Ymm0008** [comment]
问题已修改，正式版 1.0.7 可使用。 @yanbowe 感谢反馈 👍🏻
